spring.application.name=ArpegioBackend
# H2 DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.password=password
spring.datasource.username=johan

#JWT
jwt.secret=87f2ff5cc46087db4c031a77044fdb00ddc3cdbe2c0596b4793c58e1b8a3dd5f