spring.application.name=ArpegioBackend


# H2 DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.datasource.password=password
#spring.datasource.username=johan

#JWT

jwt.secret=${JWT_SECRET}
#SUPABSE CONNECTION  POSTGRESQL

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
# Usa los nombres exactos de las variables que creaste en Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate setting
spring.jpa.hibernate.ddl-update=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#DEBUG
#server.error.include-message=always
#server.error.include-binding-errors=always
#server.error.include-stacktrace=always
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.springframework.security=DEBUG